name: Deploy

on:
  push:
    branches: [ main, rewrite ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: /workspace/SPT-AKI/DB-Website

    - name: List Files
      run: ls -lah
      shell: bash
      with:
        path: /workspace/SPT-AKI/DB-Website
